# Generated by Django 5.1.7 on 2025-03-22 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('building', models.CharField(max_length=30)),
                ('capasity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=25)),
                ('bio', models.TextField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cite.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.IntegerField()),
                ('description', models.TextField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cite.faculty')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cite.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('enrollment_date', models.DateTimeField()),
                ('graduation_date', models.DateTimeField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cite.faculty')),
            ],
        ),
    ]
